---
title: "Methods_Fig4"
author: "Sarah Odell"
date: "1/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library('ggplot2')
library('data.table')
library('reshape2')
library('tibble')
library('dplyr')

founders=c("A632_usa","B73_inra","CO255_inra","FV252_inra","OH43_inra", "A654_inra","FV2_inra","C103_inra","EP1_inra","D105_inra","W117_inra","B96","DK63","F492","ND245","VA85")

mite=c(T,F,T,T,F,T,T,T,T,T,T,F,T,T,T,F)
has_mite=which(mite==T,mite)
no_mite=which(mite==F,mite)
```

```{r}
bg8=readRDS('../GridLMM_011619/bg8_genoprobs_010319.rds')

mite_start=135.947816
mite_end=135.946644
pmap=fread('../qtl2/Biogemma_071118/startfiles/Biogemma_pmap_c8.csv',data.table=F)
region=pmap[pmap$pos>135.5 & pmap$pos<136.5,]$marker
markers=dimnames(bg8[[1]])[[3]]
markers=markers[markers %in% region]
sub8=lapply(bg8,function(x) x[,,markers])
```

Calculate probability that individual has the MITE
```{r}
mite_prob=sapply(seq(1,length(region)), function(x) sapply(seq(1,344), function(i) sum(sub8[[1]][i,has_mite,x])))
rownames(mite_prob)=dimnames(bg8[[1]])[[1]]
colnames(mite_prob)=region
```

Grab phenotype data

```{r}
env="BLOIS_2014_OPT"
mite_prob=as.data.frame(mite_prob,stringsAsFactors=F)
pheno=fread('../GridLMM_011619/phenotypes.csv',data.table=F)
pheno$Genotype_code=gsub('-','.',pheno$Genotype_code)
pheno=pheno[pheno$Loc.Year.Treat==env,]
mite_prob=mite_prob[rownames(mite_prob) %in% pheno$Genotype_code,]
m=match(rownames(mite_prob),pheno$Genotype_code)
mite_prob$male_flowering_d6 = pheno[m,]$male_flowering_d6 - mean(pheno$male_flowering_d6)
```

Reformat for plotting
```{r}
#test=mite_prob[1:10,]
samples=rownames(mite_prob)

mite_prob$sample=rownames(mite_prob)
sample_f=mite_prob[order(mite_prob$male_flowering_d6),]$sample
mite_prob$sample_f = factor(mite_prob$sample,levels=c(mite_prob[order(mite_prob$male_flowering_d6),]$sample))

no_samples=dim(mite_prob)[1]

all_pr=c()
for(i in 1:no_samples){
  poi=mite_prob[i,1:281]
  sf=mite_prob[i,284]
  ft=mite_prob[i,282]
  tm=t(poi)
  mdf <- as.data.frame(tm,row.names = rownames(tm),stringsAsFactors = F)
  mdf<-rownames_to_column(mdf,"marker")
  names(mdf)=c("marker",'mite_prob')
  mdf <- merge(mdf,pmap,by.x='marker',by.y='marker')
  mdf$sample=samples[i]
  mdf$sample_f=sf
  mdf$male_flowering_d6=ft
  #mlong<-melt(mdf,id="pos")
  #mdf$sample=samples[m]
  all_pr=rbind(all_pr,mdf)
}


```

Plot

```{r}

test=all_pr[all_pr$sample_f %in% sample_f[1:20] |all_pr$sample_f %in% sample_f[305:325] ,]

pdf('mite_probability_chr8.pdf')
print(ggplot(test,aes(x=pos,y=mite_prob)) + facet_grid(sample_f~.) + geom_ribbon(aes(ymin=0,ymax=mite_prob,fill='red',alpha=5/10)) + geom_line(color='red') + ggtitle("MITE Probability, Chromosome 8") + xlab("Position (Mb)") + ylab("Probability") +  guides(alpha=FALSE) + geom_vline(xintercept=mite_start) + geom_vline(xintercept=mite_end) + theme_classic() +  theme(axis.ticks.y=element_blank(),axis.text.y=element_blank(),strip.background = element_blank(),strip.text.y = element_blank()))
dev.off()
```

```{r}
marker='AX-91102970'
at_mite=all_pr[all_pr$marker==marker,]
#drop individual with 0.5 probabilitiy
at_mite=at_mite[at_mite$sample!='EB.10H.H.00060',]
at_mite$mite_prob_f = as.factor(ifelse(at_mite$mite_prob>0.9,1,0))

ggplot(at_mite,aes(x=mite_prob_f,y=male_flowering_d6)) + geom_jitter()
```



```{r}
full_samples=dimnames(bg8[[1]])[[1]]
most_likely=founders[sapply(seq(1,344),function(x) which.max(bg8[[1]][x,,marker]))]
max_prob=sapply(seq(1,344),function(x) max(bg8[[1]][x,,marker]))
geno_probs=data.frame(sample=full_samples,mx_founder=most_likely,mx_prob=max_prob,stringsAsFactors = F)
geno_probs=geno_probs[geno_probs$sample %in% samples,]

at_mite_merge=merge(at_mite,geno_probs,by.x='sample')

#filtering
at_mite_merge=at_mite_merge[at_mite_merge$mite_prob<0.2 | at_mite_merge$mite_prob>0.8,]

at_mite_merge$has_mite=ifelse(at_mite_merge$mite_prob>0.9,T,F)
mean_ft=at_mite_merge %>% group_by(mx_founder) %>% summarize(mean_ft=mean(male_flowering_d6))

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

mean_ft$color=gg_color_hue(16)
x=c(1.5,1.5,0.5,0.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,0.5,0.5,1.5)
xend=c(2.5,2.5,1.5,1.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,1.5,1.5,2.5)
mean_lines= ggplot(at_mite_merge,aes(x=has_mite,y=male_flowering_d6)) + geom_jitter(aes(color=mx_founder)) + geom_segment(y=c(mean_ft$mean_ft[1]),yend=c(mean_ft$mean_ft[1]),x=c(x[1]),xend=c(xend[1]),colour=c(mean_ft$color[1])) + geom_segment(y=c(mean_ft$mean_ft[2]),yend=c(mean_ft$mean_ft[2]),x=c(x[2]),xend=c(xend[2]),colour=c(mean_ft$color[2])) + geom_segment(y=c(mean_ft$mean_ft[3]),yend=c(mean_ft$mean_ft[3]),x=c(x[3]),xend=c(xend[3]),colour=c(mean_ft$color[3])) + geom_segment(y=c(mean_ft$mean_ft[4]),yend=c(mean_ft$mean_ft[4]),x=c(x[4]),xend=c(xend[4]),colour=c(mean_ft$color[4])) + geom_segment(y=c(mean_ft$mean_ft[5]),yend=c(mean_ft$mean_ft[5]),x=c(x[5]),xend=c(xend[5]),colour=c(mean_ft$color[5])) + geom_segment(y=c(mean_ft$mean_ft[6]),yend=c(mean_ft$mean_ft[6]),x=c(x[6]),xend=c(xend[6]),colour=c(mean_ft$color[6])) + geom_segment(y=c(mean_ft$mean_ft[7]),yend=c(mean_ft$mean_ft[7]),x=c(x[7]),xend=c(xend[7]),colour=c(mean_ft$color[7])) + geom_segment(y=c(mean_ft$mean_ft[8]),yend=c(mean_ft$mean_ft[8]),x=c(x[8]),xend=c(xend[8]),colour=c(mean_ft$color[8])) + geom_segment(y=c(mean_ft$mean_ft[9]),yend=c(mean_ft$mean_ft[9]),x=c(x[9]),xend=c(xend[9]),colour=c(mean_ft$color[9])) + geom_segment(y=c(mean_ft$mean_ft[10]),yend=c(mean_ft$mean_ft[10]),x=c(x[10]),xend=c(xend[10]),colour=c(mean_ft$color[10])) + geom_segment(y=c(mean_ft$mean_ft[11]),yend=c(mean_ft$mean_ft[11]),x=c(x[11]),xend=c(xend[11]),colour=c(mean_ft$color[11])) + geom_segment(y=c(mean_ft$mean_ft[12]),yend=c(mean_ft$mean_ft[12]),x=c(x[12]),xend=c(xend[12]),colour=c(mean_ft$color[12])) + geom_segment(y=c(mean_ft$mean_ft[13]),yend=c(mean_ft$mean_ft[13]),x=c(x[13]),xend=c(xend[13]),colour=c(mean_ft$color[13])) + geom_segment(y=c(mean_ft$mean_ft[14]),yend=c(mean_ft$mean_ft[14]),x=c(x[14]),xend=c(xend[14]),colour=c(mean_ft$color[14])) + geom_segment(y=c(mean_ft$mean_ft[15]),yend=c(mean_ft$mean_ft[15]),x=c(x[15]),xend=c(xend[15]),colour=c(mean_ft$color[15])) + geom_segment(y=c(mean_ft$mean_ft[16]),yend=c(mean_ft$mean_ft[16]),x=c(x[16]),xend=c(xend[16]),colour=c(mean_ft$color[16]))

mean_lines


```

```{r}
library('emmeans')
mod1 = lm(male_flowering_d6 ~ mx_founder, at_mite_merge)
emeans_ft= as.data.frame(emmeans(mod1,'mx_founder'),stringsAsFactors=F)
emeans_ft$has_mite=c(T,T,F,F,T,T,T,T,T,T,T,T,T,F,F,T)

ggplot(emeans_ft,aes(x=mx_founder,y=emmean,color=has_mite)) +geom_point() + geom_errorbar(aes(ymin=lower.CL,ymax=upper.CL))
```

```{r}
gmap=fread('../qtl2/Biogemma_071118/startfiles/Biogemma_gmap_c8.csv',data.table=F)
pmap=fread('../qtl2/Biogemma_071118/startfiles/Biogemma_pmap_c8.csv',data.table=F)

rap2_7_start=136008216
rap2_7_end=136013084
haps=fread('../bg8_germline_ibd_segments.txt',data.table=F)
site=haps[haps$start>133000000 & haps$end<137500000,]


mapmerge=merge(gmap,pmap,'marker')
mapmerge=mapmerge[,c('marker','chr.x','pos.x','pos.y')]
names(mapmerge)=c('marker','chr','cM','pos')
mapmerge=mapmerge[order(mapmerge$pos),]
rownames(mapmerge)=seq(1,dim(mapmerge)[1])

m1 = match(site$start,mapmerge$pos*1e6)
start_cM = mapmerge[m1,]$cM
m2 = match(site$end,mapmerge$pos*1e6)
end_cM = mapmerge[m2,]$cM

site$start_cM=start_cM
site$end_cM=end_cM
site$start_marker=mapmerge[m1,]$marker
site$end_marker=mapmerge[m2,]$marker

cand_pos=mapmerge[mapmerge$marker==marker,]$pos*1e6
cand_block=site[site$start<cand_pos & site$end>cand_pos,]

block_start=cand_block$start_marker
block_end=cand_block$end_marker


```


```{r}
hap=readRDS('AX_91102970_haploprobs.rds')
for(i in seq(1,12)){
  hap[[i]]=as.data.frame(hap[[i]])
  hap[[i]]$hapgrp=i
  hap[[i]]=rownames_to_column(hap[[i]],"sample")
  }
all_hapgrps=c()
for(i in seq(1,12)){all_hapgrps=rbind(all_hapgrps,hap[[i]][,c(marker,'hapgrp','sample')])}

test=all_hapgrps[all_hapgrps$sample=="EB.09S.H.00081",]

max_prob=all_hapgrps %>% group_by(sample) %>% slice(which.max(`AX-91102970`))
max_prob=max_prob[max_prob$sample %in% pheno$Genotype_code,]
s=match(max_prob$sample,pheno$Genotype_code)
max_prob$male_flowering_d6=pheno[s,]$male_flowering_d6 - mean(pheno$male_flowering_d6)

```


```{r}
info=data.frame(founders=c('A632_usa','B73_inra', 'CO255_inra', 'FV252_inra' ,'OH43_inra', 'A654_inra', 'FV2_inra', 'C103_inra','EP1_inra', 'D105_inra', 'W117_inra', 'B96', 'DK63', 'F492', 'ND245', 'VA85'),hapgrp=c(1,2,3,4,5,6,7,8,9,10,11,10,12,6,9,6),has_mite=mite,hapgrp_match=c(T,T,T,T,T,F,T,T,T,F,T,F,T,F,T,F),mite_match=c(F,T,T,F,T,T,T,F,T,T,T,T,T,F,T,T),stringsAsFactors=F)

hap_info=data.frame(hapgrps=seq(1,12),mite=c("present","absent","present","present","absent","mixed","present","present","present","mixed","present","present"),stringsAsFactors = F)

h=match(max_prob$hapgrp,hap_info$hapgrp)
max_prob$has_mite=hap_info[h,]$mite
```

```{r}
ggplot(max_prob,aes(x=as.factor(has_mite),y=male_flowering_d6)) + geom_boxplot() +geom_jitter(aes(color=as.factor(hapgrp)))
```


